# **Numpy practise assignment**
 **Basic Array Creation**
1. Create an array with 10 equally spaced numbers between 0 and 1.
2. Create a 1D array of 20 random integers between 1 and 100.
3. Create a 2D array with the shape (4, 4) filled with the value 7.
4. Create a 1D array of 10 elements with the same value, 3.14.
5. Create a 2D array with the shape (3, 3) with values ranging from 1 to 9.

In [ ]:
#Create an array with 10 equally spaced numbers between 0 and 1.
import numpy as np
arr=np.linspace(0,1,10)
print("Array with 10 eqallly spaced numbers between 0 and 1:\n",arr)

#Create a 1D array of 20 random integers between 1 and 100.
random_int_arr=np.random.randint(1,100,20)
print("\n1D array of 20 random integers between 1 and 100:\n",random_int_arr)

#Create a 2D array with the shape (4, 4) filled with the value 7.
arr=np.full((4,4),7)
print("\n2D array with the shape filled with the value 7:\n",arr)

#Create a 1D array of 10 elements with the same value, 3.14.
arr=np.full(10,3.14)
print("\n1D array of 10 elements with the same value, 3.14:\n",arr)

#Create a 2D array with the shape (3, 3) with values ranging from 1 to 9.
arr=np.arange(1,10).reshape(3,3)
print("\n2D array with the shape (3,3) with values ranging from 1 to 9:\n",arr)


Array with 10 eqallly spaced numbers between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

1D array of 20 random integers between 1 and 100:
 [18 20 49 38 78 30 47 83 12 94 35 27 44 44  4 33  9  9 62 93]

2D array with the shape filled with the value 7:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

1D array of 10 elements with the same value, 3.14:
 [3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]

2D array with the shape (3,3) with values ranging from 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Operations
1. Create two arrays: a = [1, 3, 5, 7, 9] and b = [2, 4, 6, 8, 10]. Perform element-wise
subtraction.
2. Multiply array a by 3: a = [2, 4, 6, 8].
3. Divide array a by 2: a = [10, 20, 30, 40].
4. Find the element-wise modulus of two arrays: a = [5, 10, 15], b = [2, 3, 4].
5. Create two arrays: a = [1, 2, 3], b = [4, 5, 6]. Compute the dot product.

In [4]:
import numpy as np

#Create two arrays: a = [1, 3, 5, 7, 9] and b = [2, 4, 6, 8, 10]. Perform element-wise subtraction.
arr_a=np.array([1,3,5,7,9])
arr_b=np.array([2,4,6,8,10])
subtract_arr=np.subtract(arr_a,arr_b)
print("different:\n",subtract_arr)

diff_arr=arr_a - arr_b
print("\ndifferent array:\n",diff_arr)

#Multiply array a by 3: a = [2, 4, 6, 8].
arr=np.array([2,4,6,8])
multi_arr=np.multiply(arr,3)
print("\nproduct:\n",multi_arr)

multi_arr1=arr*3
print("product array:\n",multi_arr1)

#Divide array a by 2: a = [10, 20, 30, 40].
arr=np.array([10,20,30,40])
div_arr=np.divide(arr,2)
print("\ndivided array:\n",div_arr)

div_arr1=arr/2
print("divided array2:\n",div_arr1)

#Find the element-wise modulus of two arrays: a = [5, 10, 15], b = [2, 3, 4].
arr_a=np.array([5,10,15])
arr_b=np.array([2,3,4])
mod_arr=np.mod(arr_a,arr_b)
print(" \nthe element-wise modulus of two arrays:\n",mod_arr)

#Create two arrays: a = [1, 2, 3], b = [4, 5, 6]. Compute the dot product
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
dot_product=np.dot(array_a,array_b)
print("\n Dot product:\n",dot_product)

different:
 [-1 -1 -1 -1 -1]

different array:
 [-1 -1 -1 -1 -1]

product:
 [ 6 12 18 24]
product array:
 [ 6 12 18 24]

divided array:
 [ 5. 10. 15. 20.]
divided array2:
 [ 5. 10. 15. 20.]
 
the element-wise modulus of two arrays:
 [1 1 3]

 Dot product:
 32


Matrix Multiplication
1. Create two matrices: a = [[2, 3], [4, 5]] and b = [[1, 0], [0, 1]]. Perform matrix
multiplication.
2. Multiply a 3x3 matrix with a 3x1 vector.
3. Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random
integers.
4. Perform matrix multiplication on two 3x3 matrices: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
and b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]].
5. Create a 2x3 matrix and a 3x2 matrix. Perform matrix multiplication.

In [5]:
import numpy as np
#Create two matrices: a = [[2, 3], [4, 5]] and b = [[1, 0], [0, 1]]. Perform matrix multiplication.
matrix_a=([[2,3],[4,5]])
matrix_b=([[1,0],[0,1]])
matrix_multi=np.dot(matrix_a,matrix_b)
print("matrix multiplication:\n",matrix_multi)

#Multiply a 3x3 matrix with a 3x1 vector.
matrix_a=([[1,2,3],[4,5,6],[6,7,8]])
vector_b=([[10],[20],[30]])
result=np.dot(matrix_a,vector_b)
print("\nmatrix vector:\n",result)

#Create a 4x4 identity matrix and multiply it by a 4x4 matrix filled with random integers.
indentity_matrix=np.eye(4) #eye() use for indentity matrix
random_matrix=np.random.randint(1,10,(4,4))
result_matrix=np.dot(indentity_matrix,random_matrix)
print("\n indenty matrix:\n",indentity_matrix)
print("\n random matrix:\n",random_matrix)
print("\n result matrix:\n",result_matrix)

#Perform matrix multiplication on two 3x3 matrices: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]].
matrix_a=([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b=([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result=np.dot(matrix_a,matrix_b)
print("\nproduct matrix:\n",result)

#Create a 2x3 matrix and a 3x2 matrix. Perform matrix multiplication.
matrix_a=([[1,2,3],[4,5,6]])
matrix_b=([[7,8],[9,10],[11,12]])
result_matrix_multiplication=np.dot(matrix_a,matrix_b)
print("\nmatrix multiplication.\n",result_matrix_multiplication)

matrix multiplication:
 [[2 3]
 [4 5]]

matrix vector:
 [[140]
 [320]
 [440]]

 indenty matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 random matrix:
 [[4 6 3 6]
 [3 7 7 4]
 [1 1 7 9]
 [9 9 3 1]]

 result matrix:
 [[4. 6. 3. 6.]
 [3. 7. 7. 4.]
 [1. 1. 7. 9.]
 [9. 9. 3. 1.]]

product matrix:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

matrix multiplication.
 [[ 58  64]
 [139 154]]


Broadcasting
1. Create a 1D array: array = [10, 20, 30]. Subtract a scalar value, 5, using broadcasting.
2. Create a 3x3 array and a 3x1 array. Add them using broadcasting.
3. Divide a 4x4 array by a scalar value, 2, using broadcasting.
4. Create a 3x3 array and add 3 to each element using broadcasting.
5. Multiply a 1D array of shape (5,) by a 2D array of shape (5, 5) using broadcasting.

In [6]:
import numpy as np

#Create a 1D array: array = [10, 20, 30]. Subtract a scalar value, 5, using broadcasting.
arr_a= np.array([10,20,30])
scalar=5
broadcasted_array=arr_a-scalar
print("broadcasted Array:\n",broadcasted_array)

#Create a 3x3 array and a 3x1 array. Add them using broadcasting.
arr_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_b=np.array([[10],[20],[30]])
broadcasted_array=arr_a + arr_b
print("\n Add using broadcasting:\n",broadcasted_array)

#Divide a 4x4 array by a scalar value, 2, using broadcasting.
arr_a=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12,],[13,14,15,16,]])
scalar=2
broadcasted_array=arr_a/2
print("\n divide using broadcasting:\n",broadcasted_array)

#Create a 3x3 array and add 3 to each element using broadcasting.
arr_a=np.array([[1,2,3],[4,5,6],[7,8,9]])
scalar=3
broadcasted_array=array_a + scalar
print("\n Add using broadcasting:\n",broadcasted_array)

#Multiply a 1D array of shape (5,) by a 2D array of shape (5, 5) using broadcasting.
arr_a= np.array([1,2,3,4,5])
arr_b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
broadcasted_array=arr_a[:,np.newaxis]*arr_b
print("\nshaping using broadcasting:\n",broadcasted_array)

broadcasted Array:
 [ 5 15 25]

 Add using broadcasting:
 [[11 12 13]
 [24 25 26]
 [37 38 39]]

 divide using broadcasting:
 [[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]
 [6.5 7.  7.5 8. ]]

 Add using broadcasting:
 [4 5 6]

shaping using broadcasting:
 [[  1   2   3   4   5]
 [ 12  14  16  18  20]
 [ 33  36  39  42  45]
 [ 64  68  72  76  80]
 [105 110 115 120 125]]


Statistical Operations
1. Calculate the median of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
2. Calculate the mode of the array: data = [1, 2, 2, 3, 4, 4, 4, 5, 6].
3. Calculate the range of the array: data = [10, 20, 30, 40, 50].
4. Calculate the 25th percentile of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
5. Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2,
4, 6, 8, 10].

In [7]:
import numpy as np
#Calculate the median of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
data =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
median_value=np.median(data)
print("Median value:\n",median_value)

from scipy import stats
#Calculate the mode of the array: data = [1, 2, 2, 3, 4, 4, 4, 5, 6].
data=np.array([1, 2, 2, 3, 4, 4, 4, 5, 6])
mode_value=stats.mode(data)
print("\nMode value:\n",mode_value)

#Calculate the range of the array: data = [10, 20, 30, 40, 50].
data = np.array([10, 20, 30, 40, 50])
range_of_arr=np.ptp(data)
print("\nRange of array-->",range_of_arr)

#Calculate the 25th percentile of the array: data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
data=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
percentile_value=np.percentile(data,25)
print("\n25th percentile of the array-->",percentile_value)

#Calculate the correlation coefficient between two arrays: a = [1, 2, 3, 4, 5] and b = [2, 4, 6, 8, 10].

data_a =np.array([1, 2, 3, 4, 5])
data_b =np.array([2, 4, 6, 8, 10])
correlation_coefficient_value=np.corrcoef(data_a,data_b)
print("\n correlation coefficient value-->\n",correlation_coefficient_value)

Median value:
 5.5

Mode value:
 ModeResult(mode=4, count=3)

Range of array--> 40

25th percentile of the array--> 3.25

 correlation coefficient value-->
 [[1. 1.]
 [1. 1.]]


Reshaping Arrays

1. Reshape a 1D array of 12 elements to a 3x4 array.
2. Reshape a 2D array of shape (6, 2) to (3, 4).
3. Create a 4x4 array and flatten it.
4. Reshape a 3D array of shape (2, 3, 4) to (4, 3, 2).
5. Reshape a 1D array to a 2D array with 1 row and many columns.

In [8]:
import numpy as np
#Reshape a 1D array of 12 elements to a 3x4 array.
arr =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
Reshape_arr=arr.reshape(3,4)
print("Reshape Array:\n",Reshape_arr)

#Reshape a 2D array of shape (6, 2) to (3, 4).
arr =np.array([[1, 2],[ 3, 4],[ 5, 6],[7, 8],[9, 10],[11,12]])
Reshape_arr=arr.reshape(3,4)
print("\n Reshape Array2:\n",Reshape_arr)

#Create a 4x4 array and flatten it
arr =np.array([[1, 2, 3, 4],[ 5, 6, 7, 8],[9, 10,11,12],[13,14,15,16]])
flatten_array=arr.flatten()
print("\noriginal array:\n",arr)
print("\nflatten array:\n",flatten_array)


Reshape Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshape Array2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


Element-wise Operations
1. Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.
2. Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.
3. Add 10 to each element in the array: a = [1, 2, 3, 4, 5].
4. Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].
5. Square each element in the array: c = [1, 2, 3, 4, 5].

In [9]:
import numpy as np
#Create two arrays: a = [1, 3, 5] and b = [2, 4, 6]. Perform element-wise division.
arr_a=np.array([1, 3, 5])
arr_b=np.array([2, 4, 6])
result_array=arr_a / arr_b
print("element-wise division:",result_array)

#Create two arrays: a = [2, 4, 6] and b = [1, 3, 5]. Perform element-wise modulus.
arr_a=np.array([2,4,6])
arr_b=np.array([1,3,6])
result_array=arr_a % arr_b
print("\nelement-wise division:",result_array)

#Add 10 to each element in the array: a = [1, 2, 3, 4, 5].
arr = np.array([1, 2, 3, 4, 5])
result_array=arr+10
print("\n Add 10 to each element in the array:",result_array)

#Subtract 5 from each element in the array: b = [10, 20, 30, 40, 50].
arr = np.array([10, 20, 30, 40, 50])
result_array=arr-5
print("\nSubtract 5 from each element in the array:",result_array)

#Square each element in the array: c = [1, 2, 3, 4, 5].
arr = np.array([1, 2, 3, 4, 5])
result_array=arr**2
print("\n Square each element in the array:",result_array)

element-wise division: [0.5        0.75       0.83333333]

element-wise division: [0 1 0]

 Add 10 to each element in the array: [11 12 13 14 15]

Subtract 5 from each element in the array: [ 5 15 25 35 45]

 Square each element in the array: [ 1  4  9 16 25]


Slicing and Indexing
1. Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access
the element at [1, 1, 1].
2. Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11,
12]]].
3. Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60],
[70, 80, 90]].
4. Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].
5. Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50,
60], [70, 80, 90]].

In [10]:
import numpy as np
#Create a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]. Access the element at [1, 1, 1].

array_3d =np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("array 3D:\n",array_3d)
element=array_3d[1,1,1]
print("element at [1,1,1]:",element)

#Slice the first layer of a 3D array: array_3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]].

array_3d =np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
element_array=array_3d[0:1,]
print("\n actual array:\n",array_3d)
print("Slice the first layer of a 3D array:\n",element_array)

#Access all elements in the last row of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d =np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ele_arr=array_2d[-1:,]
print("\narray:\n",array_2d)
print("Access all elements in the last row of the array:\n",ele_arr)

#Access all elements in the first column of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d =np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ele_arr=array_2d[:,:1]
print("\narray_2D:\n",array_2d)
print("Access all elements in the first column of the array:\n",ele_arr)

#Slice the last two rows and columns of the array: array_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]].

array_2d =np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
ele_arr=array_2d[-2:,-2:]
print("\narray_2D:\n",array_2d)
print("Slice the last two rows and columns of the array:\n",ele_arr)

array 3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
element at [1,1,1]: 11

 actual array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slice the first layer of a 3D array:
 [[[1 2 3]
  [4 5 6]]]

array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Access all elements in the last row of the array:
 [[70 80 90]]

array_2D:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Access all elements in the first column of the array:
 [[10]
 [40]
 [70]]

array_2D:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Slice the last two rows and columns of the array:
 [[50 60]
 [80 90]]


Creating Random Arrays
1. Generate a random array of 20 elements with values between 0 and 1.
2. Create a 4x4 array with random integers between 10 and 20.
3. Create a 3x3 array with random floats between -1 and 1.
4. Generate an array of 15 random integers between 100 and 200.
5. Create a 5x5 array with random floats between 0 and 10.

In [11]:
import numpy as np

#Generate a random array of 20 elements with values between 0 and 1.
random_arr=np.random.rand(20)
print(" random array of 20 elements with values between 0 and 1:\n",random_arr)

#Create a 4x4 array with random integers between 10 and 20.
random_arr=np.random.randint(10,20,(4,4))
print("\n 4x4 array with random integers between 10 and 20\n",random_arr)

#Create a 3x3 array with random floats between -1 and 1.
random_arr=np.random.randint(-1,1,(3,3))
print("\n 3x3 array with random floats between -1 and 1\n",random_arr)

#Generate an array of 15 random integers between 100 and 200.
random_arr=np.random.randint(100,200,15)
print("\narray of 15 random integers between 100 and 200\n",random_arr)

#Create a 5x5 array with random floats between 0 and 10.
random_arr=np.random.randint(0,10,(5,5))
print("\n5x5 array with random floats between 0 and 10\n",random_arr)

 random array of 20 elements with values between 0 and 1:
 [0.91912288 0.01885065 0.25069216 0.87785886 0.99621364 0.7082347
 0.17367149 0.11891092 0.20848298 0.32851409 0.42240789 0.21318644
 0.99007666 0.64628348 0.50010123 0.69803197 0.56059685 0.45401697
 0.83712538 0.09148934]

 4x4 array with random integers between 10 and 20
 [[10 13 16 12]
 [14 13 10 16]
 [11 12 17 10]
 [15 16 13 18]]

 3x3 array with random floats between -1 and 1
 [[-1  0 -1]
 [ 0  0  0]
 [-1 -1  0]]

array of 15 random integers between 100 and 200
 [118 100 136 149 136 142 172 190 101 187 122 195 171 139 162]

5x5 array with random floats between 0 and 10
 [[1 2 6 6 3]
 [5 7 3 8 0]
 [0 6 7 4 0]
 [7 3 9 3 8]
 [0 9 5 1 7]]


Stacking and Concatenating Arrays
1. Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
2. Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].
3. Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].
4. Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10,
11, 12], [13, 14, 15], [16, 17, 18]].
5. Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b =
[[10, 11, 12], [13, 14, 15], [16, 17, 18]].

In [14]:
import numpy as np

#Vertically stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

arr_a=np.array([[1, 2], [3, 4]])
arr_b=np.array([[5, 6], [7, 8]])
Vertically_stack = np.vstack((arr_a,arr_b))
print("Vertically stack two arrays:\n",Vertically_stack)

#Horizontally stack two arrays: a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]].

Horizontally_stack = np.hstack((arr_a,arr_b))
print("\nHorizontally stack two arrays:\n",Horizontally_stack)

#Concatenate two 1D arrays: a = [1, 2, 3] and b = [4, 5, 6].

arr_a=np.array([1, 2,3])
arr_b=np.array([4,5,6])
#concatenate_arr=arr_a + arr_b
a=np.concatenate((arr_a ,arr_b))
#print("\nConcatenate two 1D arrays:\n",Concatenate_arr)
print("\nConcatenate two 1D arrays:\n",a)

#Concatenate two 3x3 arrays along rows: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10, 11, 12], [13, 14, 15], [16, 17, 18]].

arr_a=np.array([[1, 2,3],[4,5,6],[7,8,9]])
arr_b=np.array([[10,11,12],[13,14,15],[16,17,18]])
cont_arr=np.concatenate((arr_a,arr_b),axis=0)#axis=0 use for row
print("\nConcatenate two 3x3 arrays along rows:\n",cont_arr)

#Concatenate two 3x3 arrays along columns: a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and b = [[10, 11, 12], [13, 14, 15], [16, 17, 18]].

cont_arr=np.concatenate((arr_a,arr_b),axis=1)#axis=1 use for column
print("\nConcatenate two 3x3 arrays along rows:\n",cont_arr)

Vertically stack two arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stack two arrays:
 [[1 2 5 6]
 [3 4 7 8]]

Concatenate two 1D arrays:
 [1 2 3 4 5 6]

Concatenate two 3x3 arrays along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

Concatenate two 3x3 arrays along rows:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# NumPy Basics for Deep Learning

1. Basic Array Creation
1. Create a 1D array with the elements [1, 2, 3, 4, 5].
2. Create a 2D array with the elements [[1, 2, 3], [4, 5, 6]].
3. Create a 3x3 array filled with zeros.
4. Create a 2x2 array filled with ones.

In [18]:
import numpy as np
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print ("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [20]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [21]:
# Create an array with zeros
zeros_array = np.zeros((3, 3))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# Create an array with ones
ones_array = np.ones((2, 2))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1.]
 [1. 1.]]


# 2. Array Operations

1. Create two arrays: a = [1, 2, 3] and b = [4, 5, 6].
2. Perform element-wise addition, subtraction, multiplication, and division on these arrays.

In [23]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [24]:
# Addition
sum_array = np.add(a, b)
print("Sum:", sum_array)

Sum: [5 7 9]


In [25]:
# Subtraction
diff_array = np.subtract(a, b)
print("Difference:", diff_array)

Difference: [-3 -3 -3]


In [26]:
# Multiplication
product_array = np.multiply(a, b)
print("Product:", product_array)

Product: [ 4 10 18]


In [27]:
# Division
quotient_array = np.divide(a, b)
print("Quotient:", quotient_array)

Quotient: [0.25 0.4  0.5 ]


# 3. Matrix Multiplication

1. Create two matrices: matrix_a = [[1, 2], [3, 4]] and matrix_b = [[5, 6], [7, 8]].
2. Perform matrix multiplication on these matrices.

In [28]:
import numpy as np
# Create two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

In [30]:
# Matrix multiplication
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix Product:\n", matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


# 4. Broadcasting

1. Create an array: array = [1, 2, 3].
2. Multiply this array by a scalar value, e.g., 2, using broadcasting.

In [31]:
import numpy as np
# Create an array and a scalar
array = np.array([1, 2, 3])
scalar = 2

In [32]:
# Broadcasting
broadcasted_array = array * scalar
print("Broadcasted Array:", broadcasted_array)

Broadcasted Array: [2 4 6]


# 5. Statistical Operations

1. Create an array: data = [1, 2, 3, 4, 5].
2. Calculate the mean, standard deviation, and sum of this array.

In [34]:
import numpy as np
# Create an array
data = np.array([1, 2, 3, 4, 5])

In [35]:
# Mean
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 3.0


In [36]:
# Standard deviation
std_value = np.std(data)
print("Standard Deviation:", std_value)

Standard Deviation: 1.4142135623730951


In [37]:
# Sum
sum_value = np.sum(data)
print("Sum:", sum_value)

Sum: 15


# 6. Reshaping Arrays

1. Create a 1D array: array = [1, 2, 3, 4, 5, 6].
2. Reshape this array to a 2x3 array.
3. Reshape the same array to a 3x2 array.

In [38]:
import numpy as np
# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

In [39]:
# Reshape to 2x3
reshaped_array = array.reshape((2, 3))
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [40]:
# Reshape to 3x2
reshaped_array = array.reshape((3, 2))
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


# 7. Element-wise Operations

1. Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].
2. Perform element-wise addition and multiplication on these arrays.

In [41]:
import numpy as np
# Create two arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

In [42]:
# Element-wise addition
add_result = array_a + array_b
print("Element-wise Addition:", add_result)

Element-wise Addition: [5 7 9]


In [43]:
# Element-wise multiplication

multiply_result = array_a * array_b
print("Element-wise Multiplication:", multiply_result)

Element-wise Multiplication: [ 4 10 18]


# 8. Slicing and Indexing

1. Create a 2D array: array_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
2. Access the element at row 1, column 1.
3. Access row 1.
4. Access column 1.

In [44]:
import numpy as np
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [45]:
# Accessing an element
element = array_2d[1, 1]
print("Element at [1, 1]:", element)

Element at [1, 1]: 5


In [47]:
# Accessing a row
row = array_2d[1, :]
print("Row 1:", row)

Row 1: [4 5 6]


In [49]:
# Accessing a column
column = array_2d[:, 1]
print("Column 1:", column)

Column 1: [2 5 8]


# 9. Creating Random Arrays

1. Create a 3x3 array with random floats.
2. Create a 3x3 array with random integers between 0 and 10.

In [50]:
import numpy as np

# Create a random array
random_array = np.random.rand(3, 3)
print("Random Array:\n", random_array)

Random Array:
 [[0.99987786 0.54406227 0.50745017]
 [0.90649267 0.83840032 0.87699552]
 [0.35422997 0.8316917  0.7068843 ]]


In [51]:
# Create a random integer array
random_int_array = np.random.randint(0, 10, (3, 3))
print("Random Integer Array:\n", random_int_array)

Random Integer Array:
 [[6 3 2]
 [2 1 9]
 [3 6 9]]


# 10. Stacking and Concatenating Arrays

1. Create two arrays: array_a = [1, 2, 3] and array_b = [4, 5, 6].
2. Perform vertical stacking on these arrays.
3. Perform horizontal stacking on these arrays.

In [52]:
import numpy as np
# Create two arrays
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

In [53]:
# Vertical stack
v_stack = np.vstack((array_a, array_b))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [54]:
# Horizontal stack
h_stack = np.hstack((array_a, array_b))
print("Horizontal Stack:", h_stack)

Horizontal Stack: [1 2 3 4 5 6]
